(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 336,
	height: 280,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/arrows.png", id:"arrows"},
		{src:"images/bg.png", id:"bg"},
		{src:"images/_img.png", id:"_img"},
		{src:"images/logo.png", id:"logo"}
	]
};



// symbols:



(lib.arrows = function() {
	this.initialize(img.arrows);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,127,79);


(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,280);


(lib._img = function() {
	this.initialize(img._img);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,251,132);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,67,67);


(lib.特 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiHDcIAAiLQgXAIgwAOIgLg8IBSgYIAAhcIgYAAIgOBBIgwgRQASg/AFhcIAjAGQAOACAAAOIgEAiIASAAIAAheIA7AAIAABeIAgAAIAAAwIBgAAIAAgqIhXAAIAAg0IBXAAIAAgxIA9AAIAAAxIBeAAIAAA0IheAAIAAAqIBtAAIAAAzIg2AAIAAAhIA0AAIAAAzIg0AAIAABlQAAApgbALQgcALg8gKIgKg4IgRAMQgagrgigkIAdgVQAMgKAOAMQAaAXAcAoIgZASQAQADAOAAQARABAGgFQAEgEAAgJIAAhPIicAAIAAgLIgbAMIAACggAgrAIICWAAIAAghIifAAIAAgwIgYAAIAABJIAhgJg");
	this.shape.setTransform(22.3,22.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,44.6,44.1);


(lib.更 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7CCDEB").s().p("AjaCbQBAgJArgRQgYgRgVgVIAagSIAGgDIgrAAIAAjFICNAAIAAgiIiwAAIAAgyIGYAAIAAAyIiwAAIAAAiICQAAIAADFIiVAAQgJAdgSAYQBbAfCCgHIgOA6QiaAEhlguQg3AghbARgAhmBJQATAOAXAMQAQgNAIgQIhIAAIAGADgAAeAWIBVAAIAAgbIhVAAgAhtAWIBTAAIAAgbIhTAAgAAegyIBVAAIAAgdIhVAAgAhtgyIBTAAIAAgdIhTAAg");
	this.shape.setTransform(22,21.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,44,42.5);


(lib.tri = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7BCDEB").s().p("AhHhbICPBcIiPBbg");
	this.shape.setTransform(7.9,10,1.083,1.084);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,15.7,20);


(lib.logo_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.logo();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,67,67);


(lib._img_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_29 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(29).call(this.frame_29).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AwdgzIewlcICLMSI+wFbg");
	var mask_graphics_19 = new cjs.Graphics().p("AwdgzIewlcICLMSI+wFbg");
	var mask_graphics_20 = new cjs.Graphics().p("AwdhWIewlbICLMSI+wFbg");
	var mask_graphics_21 = new cjs.Graphics().p("Awdh1IewlbICLMSI+wFbg");
	var mask_graphics_22 = new cjs.Graphics().p("AwdiQIewlcICLMSI+wFcg");
	var mask_graphics_23 = new cjs.Graphics().p("AwdioIewlbICLMSI+wFbg");
	var mask_graphics_24 = new cjs.Graphics().p("Awdi8IewlbICLMSI+wFbg");
	var mask_graphics_25 = new cjs.Graphics().p("AwdjMIewlcICLMSI+wFcg");
	var mask_graphics_26 = new cjs.Graphics().p("AwdjZIewlbICLMSI+wFbg");
	var mask_graphics_27 = new cjs.Graphics().p("AwdjbIewlbICLMSI+wFbg");
	var mask_graphics_28 = new cjs.Graphics().p("AwdjbIewlbICLMSI+wFbg");
	var mask_graphics_29 = new cjs.Graphics().p("AwdjbIewlbICLMSI+wFbg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:-86.8,y:73.5}).wait(19).to({graphics:mask_graphics_19,x:-86.8,y:73.5}).wait(1).to({graphics:mask_graphics_20,x:-60.7,y:70}).wait(1).to({graphics:mask_graphics_21,x:-37.4,y:66.9}).wait(1).to({graphics:mask_graphics_22,x:-16.8,y:64.2}).wait(1).to({graphics:mask_graphics_23,x:1,y:61.8}).wait(1).to({graphics:mask_graphics_24,x:16.1,y:59.8}).wait(1).to({graphics:mask_graphics_25,x:28.5,y:58.2}).wait(1).to({graphics:mask_graphics_26,x:38.1,y:56.9}).wait(1).to({graphics:mask_graphics_27,x:44.9,y:55.3}).wait(1).to({graphics:mask_graphics_28,x:49,y:54.2}).wait(1).to({graphics:mask_graphics_29,x:50.4,y:53.8}).wait(1));

	// arrow.png
	this.instance = new lib.arrows();
	this.instance.setTransform(14,11);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30));

	// img.png
	this.instance_1 = new lib._img();

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,251,132);


(lib.copy3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F3D54E").s().p("AnQKdIAAgYIieAAIAAiYIAsAAIAABpIAgAAIAAiAIhKAAIAAiPIAsAAIAABiIAeAAIAAh/IAxAAIAAB/IAeAAIAAhiIArAAIAACPIhJAAIAACAIAhAAIAAhqIAsAAIAACxgABLKcIAAiXQgQAjgUAhIgbgsQASgZAQgfQAPggANgkIgxAAIAAgtIAyAAIAAhFIAuAAIAABFIAqAAIAAAnQAKgRAHgTQAOgkAHgrIAeAFQAIABADAEQADAEgCAIIgGAcICRAAIABCAQgCBggFAcQgDAWgGAOQgGANgJAGQgSAMgiABQgYABgigFIgHgyQASAFAjABQATgBAIgHQAFgFAEgQIgiAJIgFgZIgzALQgkAGgaADIgLgvQAKgBALgSQALgRAOgeQANgdAKgjIArAOQgKAigTAmIgWAoIA2gKIgNguIAYgHQANgDAEANQAMAjALAtQAFgeAAg7IABhXIhvAAQgTAvgbAlIgfglIAPgXIgnAAIAAAQQAnApAVAZIgeAmIgeguIAACxgAjbKbIAAhZQg5A2hJAdIgYguQBDgUA7gtIh1AAIAAgrICRAAIAAgiQgNAHgWABQgPAAgVgDIgFgrQgUAbgnAaIgcgmQATgLANgLQAOgMAHgMQAHgMADgQIgxAAIAAgoIA1AAIAAgkIAdAAQAIAAAEAEQAEAEAAAIIAAAUIBKAAQABAlgDAqQgCAqgMAMIgGAEIArAAIAAiNICQAAIAACNIiMAAIAAAiICXAAIAAArIh7AAQAbAUAgAQQAhAQAlALIgZAvQglgPghgVQghgVgdgaIAABagAkgGmIgGALQAPAEARgBQAIAAAEgFQAFgFABgdIABgVIgeAAQgEAZgLAVgAiAGtIAzAAIAAg1IgzAAgAruKYIAAiVIgSAaIgSgzQAQgaAOgfQANgfAKgkIgmAAIAAgwICKAAIAAAwIg0AAIgUA9IBDAAIAADkIgqAAIAAgdIgcAAIAAAmgArEJCIAcAAIAAhoIgcAAgAyEKQIAAgqICCAAIAAgYIhKAAIAAgXQgdATgmANIgWgpQAbgHAVgKQAVgKARgNIhLAAIAAgoIBGAAIAAhvIg+AAIAAgmIA+AAIAAgdIAyAAIAAAdIBzAAIAAgdIAxAAIAAAdIBDAAIAAAmIhDAAIAABvIBJAAIAAAoIhPAAQAMALAPAHQAWAKApAKIgUAsQgtgQgZgRIAAAXIhOAAIAAAYICGAAIAAAqgAuYIoQgQgOgPgUIhlAAQgMASgRAQIA3AAIAAgYIAwAAIAAAYIA6AAIAAAAgAwiHeIBzAAIAAgSIhzAAgAwiGwIBzAAIAAgSIhzAAgAwiGCIBzAAIAAgTIhzAAgAB7ChQAihGAAhbIAAimIDhAAIAAByIhDAAIAAAcIBNAAIAAAoIhNAAIAAAeIBCAAIAACLIgvAAIAAgXIhQAAIAAAXIgvAAIAAiLIA8AAIAAgeIg/AAQgCAygJArQgJAsgRAkgAD+B4IBQAAIAAghIhQAAgADMgYIA/AAIAAgcIg/AAgADMhdICDAAIAAghIiDAAgAl/CSQAmgIAfgOQgcgMgcgIQAPgTAOgUIgiAAIAAgqIA5AAIAOgeIAHACIAAgiQgbAYgiATIgZgkQAogSAigaIhAAAIAAgpIAeAAQgLgYgPgXIAbgLQAKgFAHAMIAUAoIgcALIAkAAIAAhCIAuAAIAABCIAhAAIgbgNQAOgTAOgeIAZAKQALAGgFALIgWAjIAaAAIAAApIhFAAIAAACQAUAIAuAaIgYAiQgUgRgWgPIAAAiIgqAAIAhAHIgKAUIBRAAIAAAhQgIATgKAQQgKAPgMANIAkATQARgLAOgLQAUgQAOgQQgRgfgOguIgOAcIghgjQAYgkAOgvQAPgvAGg4IAdAFQAQACgCAPIgGAhIBkAAIAAAuIgXAAIAAATQAABMgeA9IgIAPQAaAbApAdIgZAtQgWgQgRgQQgSgQgOgQQgPAQgTAQQgTAQgXAQIgVgcIgNAWQgbgTgbgOQgqAag3APgAk4BXIAnAOQATgQAOgUIg3AAgAiDg2QALA7ATAmQAVgsAAhBIAAgTIgqAAgAuRCdQghgNghgKIAQgbQAGgLAOADQA5AMBGAhIgfAsQghgRghgOgAyVCLQAtgFAhgKQAhgLAVgQIAKgJIiKAAIAAgsICiAAQAFgSADgrIAAhIIAjAAQAIAAAEAEQAEAFAAAIIAAA3QAAAggIAdICAAAIAAAsIiTAAQgJARgNAOQgxA2hlAOgAGxCTQBWgtAXhcIguAAIAAgiQgTARgUAPIgggpQAlgdAdgkQAdgkAVgsIAeANQANAGgGAQQgbA7guAxIDOAAQgyg0ghhPIAggOQAMgFAHAMQAuBfBIApIgfAtQgUgLgRgPQAAAugDA2QgCAggFAVQgEAUgIAIQgIAJgOAFQgNAEgTABQgaABgjgGIgIg2IAeAGIAfAAQAOAAAGgIQAEgEACgOIAFhdIhSAAQgWB1hlA7gAO4CiQAmhDAAhyIAAiNQBagBBGgOQAPgDAEANIANAiQgeAGgjAEQgkADgpACIAAA4ICcAAIAAAuIg3AAIAADHIgyAAIAAjHIgzAAQgBCBgpBHgAN0C5IAAicQgPAhgUAgIghgmQAWgaAQgfQARggALgoIgvAAIAAgsIAxAAIAAhBIAyAAIAABBIAoAAIAAAsIgoAAIAAANQAbAdAbAlIgdAeIgZgoIAAC9gAAiC0IgIgxIAYACQALAAADgDQADgEAAgFIAAhHIgmAMIgIgxIAugNIAAhHIgnAAIAAgsIAnAAIAAhCIAxAAIAABCIAeAAIAAAsIgeAAIAAA4IAfgLIAAAtIgfAMIAABtQAAAcgTAJQgLAFgUAAQgOAAgSgCgAsFC1IAAlJICJAAIAAE6IgwAAIAAggIgpAAIAAAvgArVBYIApAAIAAhJIgpAAgArVgcIApAAIAAhLIgpAAgAo3CuIgKgzIAnADQATAAAFgCQAEgDABgFIAAi3Ih0AAIAAguIB0AAIAAg6IA2AAIAAA6IApAAIAAAuIgpAAIAADIQAAAggbAIQgNAFgWAAQgVAAgdgEgApZAbQgLgbgOgaIAfgJQAMgEAHALQAVAhATA7IguATQgIgdgLgbgAx6gGIATgXQAHgJAMAFQARAGASAKIAlAVIgdAjQgngcgqgRgAxThAIATgXQAIgJAMAFQAeAMAjAZIgdAjQgkgbgngSgAtyg1IAAgxIjvAAIAAAvIg0AAIAAhdICRAAIgMgcIAmgJQAHgCAFADQAGADADAJIAIAYICOAAIAABfgAsPlIQANgNAMgQQAMgPAJgSQgLgQgKgTIgSgqIAYgNQAGgDAFADQAFACADAIIAPAeQAGgYADgaIhHAAQAWgjAohLIg4AAIAAgrIBsAAIAAAfQgSAogXAnIAoAAIAAAiQgCA1gRA0QAbAdAiALQAPAEAyADQAqAABrgGIgJAwIiIADQgaABgXgDQgXgDgTgGQgQgGgOgJQgPgKgNgNQgbAngSATgAxskoIAAiXQgQAjgUAhIgbgsQASgZAQgfQAPggANgkIgxAAIAAgtIAyAAIAAhFIAuAAIAABFIAqAAIAAAnQAKgRAHgTQAOgkAHgrIAeAFQAIABADAEQADAEgCAIIgGAcICRAAIABCAQgCBggFAcQgDAWgGAOQgGANgJAGQgSAMgiABQgYABgigFIgHgyQASAFAjABQATgBAIgHQAFgFAEgQIgiAJIgFgZIgzALQgkAGgaADIgLgvQAKgBALgSQALgRAOgeQANgdAKgjIArAOQgKAigTAmIgWAoIA2gKIgNguIAYgHQANgDAEANQAMAjALAtQAFgeAAg7IABhXIhvAAQgTAvgbAlIgfglIAPgXIgnAAIAAAQQAnApAVAZIgeAmIgeguIAACxgApDlkIAAgbIhbAAIAAgmIBbAAIAAgSIhHAAIAAgkIBHAAIAAgRIhDAAIAAglIBDAAIAAgTIhVAAIAAgmIBVAAIAAgUIg/AAIAAglIA/AAIAAgXIAxAAIAAAXIBZAAIAAA5IAcAAIAAAmIgcAAIAAA4IhZAAIAAARIBbAAIAAAkIhbAAIAAASIBtAAIAAAmIhtAAIAAAbgAoSoRIApAAIAAgTIgpAAgAoSpKIApAAIAAgUIgpAAg");
	this.shape.setTransform(122.2,70.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(2.5,3.5,239.4,133.9);


(lib.bg_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bg();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,336,280);


(lib.ctaText = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.更("synched",0);
	this.instance.setTransform(57.8,13.9,0.47,0.47,0,0,0,22,21.1);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7CCDEB").s().p("ADjBOQAdgDAagGQAZgGAVgIIABAAIgUgSIAOgKQAGgFAHAFQAIAGAJAKQAUgMARgPIg3AAQgiAXgtAOIgRgXQAcgHAYgMQAXgLAVgOQglAQg6AHIgMgWQAqgEAigLQgJgJgKgHIAPgLQAFgEAGAFQAIAGAJAKQAUgKAPgOIg8AAQgZASggAMIgRgWQAZgIAVgMQAVgMASgRIASAEQAFABAAACQAAACgCAEIgFAFIBHAAIAAATQgLANgNALQgNAMgQAJIAPAEQAIABgGAHIgCADIBDAAIAAARQgeAmgsAXQgWAMgdAIQgcAIgkAEgAjbBaQAGgMADgPQADgPAAgTIAAhAIgMgLQALgMAJgOQAIgOAGgRIASAEQAGABgDAIIAAACIAjAAIAAARQgFAMgHALIAUAAIAAAKQAPgIAIgJQAEgFADgIIgZAAIAAgXIBhAAQABASgCAUQgBAVgHAGQgDACgFACQgGABgHAAQgJABgMgCIgDgZQAJACAKAAQAEAAACgDQACgCAAgNIABgFIgXAAIgEAQIgHANQgJAMgWALIgLgTIAAB4QAAAKgHADQgGAEgOgDIgFgaIAHAAQABAAABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIAAgWIgLAAIAAAyIgVAAIAAgyIgLAAQgDAegJAYgAiaAbIALAAIAAgSIgLAAgAi5AbIAKAAIAAgSIgKAAgAiagKIALAAIAAgQIgLAAgAi5gKIAKAAIAAgQIgKAAgAi6gwIATAAIAMgSIgTAAgAhMBlIAAgnIgqAAIAAgXIAqAAIAAgSIgQAAIgHAPIgVgKQAJgRAFgaIAQADQAGACAAAGIgCAFIAKAAIAAgSIAaAAIAAASIAfAAIAAAWIgfAAIAAASIAlAAIAAAXIglAAIAAAngAmGBiIgHgfIAdACQALABADgCQAEgCABgFIAAhYIACAAIAvgiIiBAAIAAgaICwAAIAAAXIhCAzIAABTQAAASgPAHQgIAFgVAAIgbgCg");
	this.shape.setTransform(47.1,13.1);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(4.1,2.7,86.1,21.3);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});



this.frame_arrow = function() {
		if(tmp>1){
		this.parent.stop();}
		}
	// tri
	this.instance = new lib.tri("synched",0);
	this.instance.setTransform(105.5,11,1,1,0,0,0,6.5,8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(24).to({startPosition:0},0).to({x:109.5},5).to({x:105.5},5).to({x:109.5},5).to({x:105.5},5).wait(1).call(this.frame_arrow).wait(1));;

	// Layer 1
	this.instance_1 = new lib.ctaText("synched",0);
	this.instance_1.setTransform(34.2,9.9,1,1,0,0,0,34.2,9.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(45));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.1,2.7,110.7,21.3);


(lib.copy2 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.特("synched",0);
	this.instance.setTransform(137.2,73.1,0.51,0.51,0,0,0,22.2,21.9);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALvIoQgHgDgEgEQgFgFgCgGQgDgHAAgHQAAgIADgGQACgGAFgFQAEgFAHgDQAHgCAHAAQAHAAAHACQAGADAEAFQAFAFADAGQADAGgBAIQABAHgDAHQgDAGgFAFQgEAEgGADQgHADgHAAQgHAAgHgDgALyH8QgFAFABAHQgBAGAFAFQAEAFAHAAQAGAAAEgFQAGgFgBgGQABgHgGgFQgEgEgGAAQgHAAgEAEgAzUINQAhgTAXgbQgOgYgHgcQgIANgKANIgVgUQAlgyAGg6IAUABQAHAAAAAJIgDATIA7AAIAAAXQgBAfgJAaQgHAbgNAXQAUAVAfAIQAKADAdAAIAsgCIgHAgIguABQgSAAgPgDQgTgEgRgKQgQgJgNgOQgLANgOALQgOAMgPAJgAyMHHQASggADgpIglAAQACArAOAegACuIYQgLgJgJgJQgHgHgGgMQgIgMgHgQIgHARQgRAigvAeIgTgbQAogXAOgZIAGgNIgpAAIAAgcIAwAAQABgLABgMIAAgdIgrAAIAAgcIArAAIAAgcIAUAAQAFAAADACQACADAAAFIAAASIA8AAIAABQIASAAIAAAcIg8AAQALAVAMALQAPAPAaANIgTAcIgYgQgACHGdIgBAXIAeAAIAAg0IgdAAgAj+IbQAGgNADgRQADgRAAgVIAAhJIgNgMQAMgNAKgQQAJgQAHgTIASAFQAIABgEAJIAAACIAoAAIAAATQgHANgHAMIAWAAIAAALQARgIAIgKQAFgFADgKIgbAAIAAgZIBrAAQAAAUgCAWQgBAXgHAGQgEAEgGABQgFACgJAAQgKAAgMgCIgEgbQAKACALAAQAEAAACgDQACgCABgPIAAgGIgZAAQgBAKgDAIQgDAIgEAHQgLANgYAMIgMgVIAACHQAAALgHAEQgIAEgPgDIgFgdIAIAAQADAAAAgEIAAgXIgMAAIAAA2IgYAAIAAg2IgLAAQgDAggLAbgAi3HVIAMAAIAAgUIgMAAgAjZHVIAKAAIAAgUIgKAAgAi3GpIAMAAIAAgRIgMAAgAjZGpIAKAAIAAgRIgKAAgAjaF/IAUAAIAOgUIgWAAgAJDInIAAg3QgiAlgwARIgOgZQARgFARgIQAQgIAPgLIg5AAIAAgYIBYAAIAAgRIgPADQgYAEggAAIgKgWQAnABAegGQgVgEgVgCIATgVIgzAAIAAgWIBCAAIALgRIAaAFIgIAMIBvAAIAAAWIgrAAQgJAMgMAKQAbAGAcAKIgQAUQgggMgggJIgEACIgSAGIAWAAIAAATIBZAAIAAAYIg4AAQAOAKARAHQARAIASAGIgPAaQgXgJgWgOQgVgOgSgRIAAA3gAI1GfIAnAFQAMgGAKgJIg1AAgAhiInIAAgrIgtAAIAAgaIAtAAIAAgUIgRAAIgIARIgXgLQAKgTAGgfIARAEQAHACgBAHIgCAFIALAAIAAgUIAdAAIAAAUIAiAAIAAAaIgiAAIAAAUIAoAAIAAAaIgoAAIAAArgAo5InIAAgJIgcAAIAAAJIgcAAIAAhOIA0AAQgfgMgTgVIgRAAQgLAOgRAJIgUAKIAxAAIAABOIgbAAIAAgJIgcAAIAAAJIgbAAIAAhEIgPADIgLgYQAmgFAZgOIADgDIg2AAIAAgWIBOAAIAIgOIhLAAIAAhEIBUAAIAABBIAJABQAKABgCAJIgDAGIAtAAIgNgHIAHgIIgmAAIAAhDIBWAAIAABDIgbAAIAMAGIgHAJIAjAAIAAAWIg8AAQANAIARAFQASAFAXAEIgKAYIgQgDIAABEgApVIGIAcAAIAAgWIgcAAgAq2IGIAcAAIAAgWIgcAAgAq4F9IAcAAIAAgWIgcAAgApVF8IAeAAIAAgWIgeAAgADvIQQAjgfANgiQAHgRADgWQADgUAAgYIg4AAIAAgbIBVAAIgIgWIAYgGQAEgCAEACQADADADAFIAGAUIBaAAIAAAbIh7AAQAAASgCAQIBoAAQAAAvgCAbQgCAngKALQgGAFgJADQgJADgNAAQgTABgYgDIgEggQAOACAbABQALgBAGgFQAFgFACgeIABgiIhMAAQgDAPgEANQgIAUgOAUQgNAUgUATgAlrIhIgGghQAQAFAQgBQAJgBAEgDQAFgEADgRQACgRAAgmIABgxIgsAAQgNAbgJAMIANgGQAFgDADABQADABADAFQAPAfAIATIgaANQgJgVgTgmIACgBIgQgLIAACAIgdAAIAAgUIgiAAIAAAYIgdAAIAAjBIAbAAIAFgfIAWABQAFABADADQABADAAAFIgEASIAhAAIAAAuQAUghAKguIAWAFQAHACgDAKIgFAUIA/AAIABBLQAAAxgEAZQgCANgDAIQgEAIgFAEQgGADgHACQgHACgKAAIgEAAQgMAAgRgDgAnMHvIAiAAIAAgrIgiAAgAnMGpIAiAAIAAgqIgiAAgAgLIRQALgWAJgWQAKgXAHgYIAbAMQgGAZgKAYQgKAZgNAYgAuWIgIAAgbIA+AAIAAgUIg2AAIAAgaIA2AAIAAgSIgzAAIAAhyICDAAIAAByIg0AAIAAASIA1AAIAAAaIg1AAIAAAUIA9AAIAAAbgAs8GrIAYAAIAAgTIgYAAgAtwGrIAYAAIAAgTIgYAAgAs8GAIAYAAIAAgSIgYAAgAtwGAIAYAAIAAgSIgYAAgAvgH2IAbgIIAAg6IgXAAIAAgaIAXAAIAAgwIgYAAIAAgaIBMAAIAAAaIgWAAIAAAwIASAAIAAAaIgSAAIAAAwIAUgHIAAAcQggAOgoAMgAxFH7IAAi0IAeAAIAAA2QAgAUAYAYIgUAZQgYgagMgKIAABdgAAMF7QgKgSgJgRIARgJQAHgDAGAHQAPAVAPAmIgZARQgIgTgIgRgAKcF6IAAgNIiRAAIAAANIgcAAIAAglIBTAAIgEgMIAVgGQAFgBACACQAEACACAFIADAKIBVAAIAAAlgARLD0Qg3AIg4ADIgFgdIA4gEIAAgaIgxAAIAAhIIAxAAIAAgQIgqAAIAAhEIByAAIAABEIgqAAIAAAQIAxAAIAABIIgxAAIAAAYIASgCIgHgLIARgIQAHgDAEAHQAHALAQAiIgaAOgAQtCqIAUAAIAAgVIgUAAgAP7CqIAUAAIAAgVIgUAAgAQFBTIAyAAIAAgTIgyAAgAxsDuQgegLgggHIALgSQABgEAEgBQADgCAEABQA0AKA/AcIgQAcQgdgOgfgKgAhOD6QgSgHgOgKIgRgNIgOgRQgOAVgZAOQgaAOglAIIgNgbQA8gLAZgdIhQAAIAAgbIAbAAIAAg7IBFAAIAAgVIAUAAQAEAAADADQACACAAAFIAAALIBFAAIAAA7IAdAAIAAAbIhVAAQAKAKALAHQALAHARAGQARAGAVAEIgLAcQgXgEgSgHgAh/CmIApAAIAAghIgoAAgAjDCmIAlAAIADgQIAAgRIgoAAgAu9ECIAAhOIgQAQIgSgXQATgUAQgVQAQgWANgYIg2AAIAAgcIBCAAIAJgaIAUABQAKgBgCALIgEAPIBsAAIAAAcIh3AAIghA4IAAB0gAEvEAIgHghQAfAEAEgDQAFgCAAgFIAAh2IAgAAIAACAQAAASgMAIQgGADgNABIgJABQgKAAgPgCgAOTEAIgHghQAMACAOABQAIAAADgEQADgDABgJIABgjIguAAQAIgsABglIAnAAIAAgbIgvAAIAAgbIBNAAIAABRIgqAAIgDAbIAsAAQgBBGgEAOQgCAIgEAEQgEAFgEACQgKAGgLAAgAm7D/IgHggIAcACQALAAADgBQAFgCAAgGIAAg6IhaAAIAAgeIBaAAIAAgxIhKAAIAAgcIC1AAIAAAcIhJAAIAAAxIBaAAIAAAeIhaAAIAABEQAAAKgEAGQgDAGgIAEQgGADgPABIgLABIgbgCgArXD7IAAgaIBPAAIAAgPIgtAAIAAgOQgSAMgXAIIgNgZQAQgEANgGQANgGAKgJIgtAAIAAgYIArAAIAAhDIgnAAIAAgXIAnAAIAAgTIAeAAIAAATIBGAAIAAgTIAeAAIAAATIApAAIAAAXIgpAAIAABDIAsAAIAAAYIgwAAQAIAHAJAFQANAGAaAGIgNAaQgcgJgPgKIAAANIgwAAIAAAPIBSAAIAAAagApHC7QgKgIgJgNIg+AAQgHAMgLAJIAiAAIAAgOIAdAAIAAAOIAkAAIAAAAgAqbCOIBGAAIAAgLIhGAAgAqbByIBGAAIAAgLIhGAAgAqbBWIBGAAIAAgLIhGAAgAuWD3IAAgdIA4AAIAAgyIgwAAIAAgdIAwAAIAAgrIAgAAIAAArIAxAAIAAAdIgxAAIAAAyIA7AAIAAAdgAKbD2IAAgcIBXAAIAAgXIhPAAIAAgcIBPAAIAAgVQgzABgTgBIgDgeQAJgCAJgGQAHgHAMgOIAIgKIg1AAIAAgbIDDAAIAAAbIhqAAIgRAWIgUAUIAjAAQAdgBAcgDIgSgUIAQgLQAFgFAHAHQAVAUAZAfIgYAQIgLgOQgZAEgaACIAAAWIBQAAIAAAcIhQAAIAAAXIBZAAIAAAcgAzYDOQAQgVAHgYQAIgYAAgbIAAhEICtAAIAABZIgbAAQAWAsAhAVIgUAbQgrgggWg8IhWAAQgFA3geApgAyaBnIBvAAIAAghIhvAAgAGcC0QgNgUgPgRIAQgLQAHgFAHAIQAeAgAVAnIgbARQgMgWgOgVgADrDKQARgPANgSQANgSALgWIARAIQAJAFgEAJQgSAlghAjgAyPCqIAKgQQAEgHAJACQAOAEARAGQARAHASAJIgOAZQgkgTgngLgASZCLQgIgDgGgGQgGgGgEgIQgDgJAAgKQAAgLADgIQAEgIAGgGQAGgGAIgEQAJgDAKAAQAJAAAJADQAIAEAHAGQAGAGAEAIQADAIAAALQAAAKgDAJQgEAIgGAGQgHAGgIADQgJADgJAAQgKAAgJgDgASeA/QgHADgFAFQgEAEgCAHQgEAHAAAIQABAIACAGQACAHAFAFQAGAFAGACQAGADAIAAQAPAAALgKQAEgFADgHQACgGAAgIQAAgIgCgHQgDgHgEgEQgFgFgHgDQgGgCgIAAQgIAAgGACgAH/CLQgIgDgHgGQgGgGgDgIQgDgJAAgKQAAgLADgIQADgIAGgGQAHgGAIgEQAIgDAKAAQAKAAAIADQAJAEAHAGQAFAGAEAIQAEAIgBALQABAKgEAJQgEAIgFAGQgHAGgJADQgIADgKAAQgKAAgIgDgAIDA/QgGADgFAFQgFAEgCAHQgDAHAAAIQAAAIACAGQADAHAFAFQAFAFAHACQAGADAHAAQAQAAAKgKQAFgFACgHQADgGAAgIQAAgIgDgHQgCgHgFgEQgFgFgGgDQgHgCgIAAQgHAAgHACgADvB0QAhgjARgzIAWAFQADABABADQABADgBAFIgDAJICKAAIAAAZIgQAvIgegHIAPglIh3AAQgIAOgIAOQgKANgLAMgAS3B2IgNgRIgDAAIgCAAIAAARIgMAAIAAgtIAVAAQAIAAAFAEQAFADAAAHQAAAFgDADQgDADgFABIAOATgASlBeIAFAAQAKAAAAgHQAAgEgDgCIgIgBIgEAAgAIcB2IgMgRIgEAAIgCAAIAAARIgLAAIAAgtIAUAAQAIAAAGAEQAEADAAAHQAAAFgCADQgEADgFABIAPATgAIKBeIAGAAQAJAAAAgHQAAgEgCgCIgIgBIgFAAgAhvBeIAAgTIg7AAIAAATIgeAAIAAgTIgxAAIAAgbIAxAAIAAgQIAeAAIAAAQIA7AAIAAgQIAeAAIAAAQIAzAAIAAAbIgzAAIAAATgALwgMQAEgJAEgJQACgKAAgLIgMAAIAAgoIAmAAIAAAXQAAASgEARQgCAQgJAOgAm1gvQAVgrAAg3IAAhnICJAAIAABGIgpAAIAAARIAvAAIAAAZIgvAAIAAATIApAAIAABUIgdAAIAAgNIgxAAIAAANIgdAAIAAhUIAkAAIAAgTIgmAAQgBAfgGAaQgFAbgLAWgAllhIIAxAAIAAgUIgxAAgAmEihIAmAAIAAgRIgmAAgAmEjLIBRAAIAAgUIhRAAgArrg4QAXgFATgJIgigMIASgYIgVAAIAAgZIAiAAIAJgUIAFABIAAgUQgRAOgUANIgQgXQAYgLAVgQIgnAAIAAgZIATAAQgIgOgJgOIARgHQAGgDAEAHIAMAYIgRAHIAXAAIAAgoIAbAAIAAAoIAUAAIgQgIQAJgMAIgSIAQAGQAGAEgDAHIgNAVIAQAAIAAAZIgrAAIAAABQANAFAbAQIgOAVQgMgLgOgJIAAAVIgaAAIAVAGIgGAMIAxAAIAAAUQgFALgGAKQgGAKgHAIIAWALIATgOQAMgJAIgKQgKgTgIgcIgJARIgUgWQAPgXAJgcQAIgdAEgiIASADQAJABgBAKIgDATIA8AAIAAAcIgNAAIAAAMQAAAwgTAlIgFAJQAQARAaARIgQAcQgNgKgLgKIgUgTQgIAKgMAKIgaATIgMgRIgIANQgRgLgRgJQgZAQgiAJgArAhcIAXAIQANgJAIgNIgiAAgApSi0QAHAmAMAXQANgcAAgoIAAgMIgZAAgAvkg0QAHgIANgLQAFgGAHgCIAAhBIgaAAIAAgdIA3AAIAABdIAQAHQATAKAkAAQAaAAAagCQAZgCAYgEIgEAfQhCAFgfAAQgTAAgOgCQgOgDgJgFQgUgJgFAAQgHAAgIAHQgHAHgGAJgAj5g4QA1gbAPg4IgdAAIAAgWIgYAVIgTgbQAWgRASgWQARgWAOgbIASAIQAIAEgEAJQgRAkgcAeIB+AAQgegfgUgxIAUgIQAHgDADAHQAdA6AsAZIgTAdQgMgIgLgKQAAAegCAhQgBATgCANQgEAMgFAFQgEAGgIADQgIACgMABQgQAAgWgDIgEghIATADIASABQAJgBADgEQACgDACgJIADg4IgyAAQgNBIg+AjgAHjg6QAwgjARgnQALgXAEggIg+AAIAAgdIBAAAIAAgrIAYAAQAEAAACADQADACAAAFIAAAhIBbAAQgBBNgCAnQgCAogMALQgHAGgJADQgIADgLAAQgSAAgbgDIgGghQAZADATAAQAGAAAEgCQAEgBACgEQAEgGADgUIADhUIg9AAQgEAjgMAeQgKAXgTAXQgSAWgbAWgACXggIAAh7IgfAAQAABQgZArIgcgOQAXgpAAhHIAAhWQA2gBArgIQAJgCADAIIAIAUQgSAEgWACQgVADgaABIAAAiIBfAAIAAAcIghAAIAAB7gAAZggIAAhgQgJAUgMAUIgSgXQANgQAIgUQAKgUAHgYIgbAAIAAgbIAcAAIAAgoIAeAAIAAAoIAYAAIAAAbIgYAAIAAAIQARASAQAXIgSATIgPgaIAAB1gAD5ghIAAiNIBjAAIAABxQgBAIgCAGQgDAFgFADQgGADgKABQgLABgPgCIgGgcQAYACADgCQAEgDAAgEIAAgHIgsAAIAAAtgAEUhkIAsAAIAAgPIgsAAgAEUiIIAsAAIAAgNIgsAAgAnsgkIgEgdIAPABQAGAAACgCQACgCAAgDIAAgsIgXAIIgFgeIAcgJIAAgsIgYAAIAAgbIAYAAIAAgoIAeAAIAAAoIASAAIAAAbIgSAAIAAAjIATgHIAAAcIgTAIIAABCQAAARgLAGQgHADgMAAIgVgCgAzZg4QAjgzADhSIgeAAIAAgdIAeAAIAAgoIAWAAQAEAAADACQACADAAAFIAAAeIAxAAIAABHQAAAtgDAYQgBAMgDAIQgDAIgEADQgJAHgPAAIgZgBIgEghQAKADALAAQAGgBADgDQADgEABgQQABgQABgjIAAgrIgSAAQgCBbgpA/gAwagmIAAgTIgdAAIAAATIgeAAIAAjCIBaAAIAADCgAw3hVIAdAAIAAh3IgdAAgAGCgnQgagCAAgXIAAhSIAeAAIAAAcQAZgHAWgIQADgCAEABQADABACAEIALAQQgiANgkAIIAAARQAAAHAGABIAMABIALgBQAIgBADgEQADgDABgRIAaANQgBAUgGAJQgIAKgSABgAtdhEIAAgzQgJANgMALQgMAKgPAJIgSgXQAPgHAMgJQANgJAMgMIgnAAIAAhDIA1AAIAAgQIg/AAIAAgZIA/AAIAAgQIAfAAIAAAQIA9AAIAAAZIg9AAIAAAQIAyAAIAABDIglAAQAQAMAjAgIgWASQgUgXgWgWIAAAzgAs+igIAXAAIAAgSIgXAAgAt2igIAZAAIAAgSIgZAAgAGCiYQgagCgBgXIAAgMIgUANIgHgNQgVADgXACIgrABIgFgZQAGgCAGgFQAFgGAIgLQAHgKAGgOIAdAGQgGANgJANIgOAQIApgEIgPgVIAOgIQAFgEAGAGQARAVANAYIAAg4IAeAAIAAAaQAYgHAUgHQAIgEAFAHIAKAQQgQAGgRAFIgiAIIAAAOQAAAHAHABIASAAQAJgBABgDQADgEABgPIAaAMQgBATgGAIQgIAJgRABgAvdjwIANgMQAHgGAGAFQAUAQARATIgUAVQgWgZgVgSgAEEkxQAFgJACgJQADgKAAgLIgMAAIAAgoIAlAAIAAAXQAAASgCARQgDAQgIAOgAm1lUQAVgrAAg3IAAhnICJAAIAABGIgpAAIAAARIAvAAIAAAZIgvAAIAAATIApAAIAABUIgdAAIAAgNIgxAAIAAANIgdAAIAAhUIAkAAIAAgTIgmAAQgBAfgGAaQgFAbgLAWgAllltIAxAAIAAgUIgxAAgAmEnGIAmAAIAAgRIgmAAgAmEnwIBRAAIAAgUIhRAAgArrldQAXgFATgJIgigMIASgYIgVAAIAAgZIAiAAIAJgUIAFABIAAgUQgRAOgUANIgQgXQAYgLAVgQIgnAAIAAgZIATAAQgIgOgJgOIARgHQAGgDAEAHIAMAYIgRAHIAXAAIAAgoIAbAAIAAAoIAUAAIgQgIQAJgMAIgSIAQAGQAGAEgDAHIgNAVIAQAAIAAAZIgrAAIAAABQANAFAbAQIgOAVQgMgLgOgJIAAAVIgaAAIAVAGIgGAMIAxAAIAAAUQgFALgGAKQgGAKgHAIIAWALIATgOQAMgJAIgKQgKgTgIgcIgJARIgUgWQAPgXAJgcQAIgdAEgiIASADQAJABgBAKIgDATIA8AAIAAAcIgNAAIAAAMQAAAwgTAlIgFAJQAQARAaARIgQAcQgNgKgLgKIgUgTQgIAKgMAKIgaATIgMgRIgIANQgRgLgRgJQgZAQgiAJgArAmBIAXAIQANgJAIgNIgiAAgApSnZQAHAmAMAXQANgcAAgoIAAgMIgZAAgAidlFIAAhOIg0AAIAAAQIggAAIAAh6IBUAAIAAgiIAfAAIAAAiIBYAAIAAB6IggAAIAAgQIg4AAIAABOgAh+muIA4AAIAAg0Ig4AAgAjRmuIA0AAIAAg0Ig0AAgAu9lFIAAh1IgSAWIgTgdQAngnAWhCIATAHQAFACABAEQACADgCAFQgIAVgKAUIAACngAyalaIAAAVIgfAAIAAh3IgRAYIgOgkQAkgrAPg2IAVAIQAIADgDAJIgPAkIAACWQANgPAJgQQAJgQAEgQQAEgMADgQIACggIgjAAIAAgcIAkAAIAAgyIAVAAQAEAAADADQADACAAAFIAAAoIBVAAIAAAcIgqAAIAABoQAAAGAFABIAFAAIAFAAQAHgCABgJIABgeIAcAOQAAAfgFAMQgEAGgFAEQgGAEgJABIgPABIgNgBQgZgDAAgWIAAh1IgOAAQgBASgDARQgCARgEAQQgGAUgJATQgLATgOATgAnslJIgEgdIAPABQAGAAACgCQACgCAAgDIAAgsIgXAIIgFgeIAcgJIAAgsIgYAAIAAgbIAYAAIAAgoIAeAAIAAAoIASAAIAAAbIgSAAIAAAjIATgHIAAAcIgTAIIAABCQAAARgLAGQgHADgMAAIgVgCgAtZlJQgOgCgIgHQgHgHAAgMIAAgrIgYANIgPgdQAVgKASgMIAAhsIAfAAIAABVQARgNAOgQQAPgPANgSIAQAMQAFADAAAEQAAADgCAEQgQAWgTATQgUAUgXAQIAAAyQAAAIAIACIAjAAQAGgCADgHQABgIABghIAgAQQAAAggHAPQgEAHgGAFQgIAEgKACIgaAAIgbAAgABNlLQgbgDAAgXIAAiRIAgAAIAACCQAAAHAHACIAqAAQAEgCACgIQACgHABghIAfAPQAAAigHAPQgEAIgGAEQgHAEgIACgAgHluQAOgqADhCIAVACQAIABAAAJQgCAegFAbQgEAagJAWgACfnWIATgFQAEgBADACQADACACAFQAKAYAGAZQAHAZADAZIgdAHQgJg7gTgygABKoWIAPgLQAIgFAHAHIAXAcQAMAPAKAPIgaATQgZgogYgcgAxDoXIAOgMQAFgFAHAFQAQAKARARIgVATQgZgYgNgKg");
	this.shape.setTransform(127.1,58.6);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(2.9,3.1,248.5,111.1);


(lib.copy1 = function() {
	this.initialize();

	// Layer 2
	this.instance = new lib.特("synched",0);
	this.instance.setTransform(55.3,20,0.74,0.74,0,0,0,22.2,22.1);
	this.instance.alpha = 0.801;

	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.8)").s().p("AJgItQgigSgmgOIAPgWQAHgLANAFIAtAUIAZgiIhsAAIAWhIIgjAAIAAAhIgkAAIAAAdIAigIIAAArIgiAIIAABKIgpAAIAAhCIg/AKIgHgrIBGgKIAAglIg6AAIgJgoQAIgEAEgIIAQg3IgcAAIAAgmIAmAAIAJgoIAnAGIgIAiIBBAAIAAAmIhLAAIgUBDIATAAIAAgqIApAAIAAAqIAgAAIAAgfIAyAAIAJgjIgvAAIAAgnIA3AAIAGgeIArABIgGAdIBFAAIAAAnIhNAAIgJAjIBhAAIAAAmIhsAAIgKAiIBsAAIAAAeQgUAggYAcIAvAbIgYAjQgggXgjgRgAuOI4IALgPQghAIgjAGQgnAIgrAFIgIgsIAagDIAAj4IB9AAIAADkIAPgDIAAAdQAlhBAAhfIAAgTIgoAAIAAgpIAoAAIAAg2IAcAAQAIAAADAEQAEAEAAAGIAAAoIBMAAIAABrQgBBQgDAYQgCASgEAMQgEALgHAFQgGAEgJADQgIADgMABQgQAAgVgEIgIgvQARAGARgBQAKAAAEgGQAEgGADgXQACgZAAg0IABhFIghAAIAAATQAACHg9BNgAveIQIArgIIAAgpIgrAAgAveG6IArAAIAAgpIgrAAgAveFtIArAAIAAgqIgrAAgAq5IpQBHgzAZg5QAPghAGgvIhaAAIAAgqIBeAAIABg+IAgAAQAIAAADAEQAEADAAAHIgBAwICFAAQAABxgFA4QgDA5gSARQgJAJgMAFQgNADgQAAQgaABgngEIgIgxQAiAEAeABQAIgBAGgCQAFgDAEgEQAGgKAEgdQADg4ABhCIhYAAQgHAzgRArQgPAigbAiQgaAggoAfgAlKJGIAAgnIAtAAIAAiIIArAAIAACIIA0AAIAAi4IAuAAIAABDIBZAAIAAAnIhZAAIAABOIB7AAIAAAngALkJFIAAgnICGAAIAAgZIh1AAIAAgnIB1AAIAAgXIAuAAIAAAXIB5AAIAAAnIh5AAIAAAZICMAAIAAAngAAbJCIAAgrIBaAAIAAkNIAuAAIAAENIAlAAIAAkNIAuAAIAAENIBdAAIAAArgAD8HbQAOgjAMgoQAMgoAJguIAgAIQAMAEgDAPQgIAogMAmQgMAlgPAkgAAVFEIAdgHQAMgEAGANQAMAcAKAnQAKAlAIAwIgqANQgOhWgfhRgALhG0QALgKAHgMQAIgLAFgNIgdAAIAAgjIAmAAIABgrIgcAAIAAgjICnAAIAAAjIgZAAIAAArIAhAAIAAAjIghAAIAAA8IgqAAIAAg8IglAAQgLArgfAegAMyFjIAgAAIAAgrIggAAgAPAHLIgIgqQAPADAOAAQANAAAEgCQADgDAAgGIAAiQIAsAAIAACgQAAAagUAHQgLAEgQAAIgEAAQgPAAgTgDgAhsFvQglgYgfgfQg5A7hSAlIgZgjQBhgsA8hFIAeAGQAPADgJAMIgBACQA3A3BWAhIgYAmQgpgRgkgZgAOpGRIAAh1IApAAIAAB1gAj5CMQAeg9ABhQIAAiUIDIAAIAABlIg8AAIAAAZIBEAAIAAAjIhEAAIAAAbIA7AAIAAB7IgqAAIAAgUIhHAAIAAAUIgpAAIAAh7IA0AAIAAgbIg4AAQgBAtgIAmQgJAngPAggAiEBoIBHAAIAAgdIhHAAgAixgXIA4AAIAAgZIg4AAgAixhUIB1AAIAAgdIh1AAgAq7CAQAhgIAcgMQgZgLgZgHQANgRAMgSIgdAAIAAglIAyAAIAMgaIAHABIAAgeQgYAWgeARIgXggQAkgQAegXIg5AAIAAglIAbAAQgKgVgOgUIAYgKQAJgEAHAKIASAjIgZAKIAgAAIAAg6IAoAAIAAA6IAeAAIgZgLQAOgSAMgaIAWAJQAKAFgFAKIgUAfIAYAAIAAAlIg+AAIAAACQATAGAoAYIgVAeQgSgPgUgOIAAAeIglAAIAdAHIgIARIBHAAIAAAeQgHAQgJAOQgIAPgLALIAgARQAPgKANgKQARgPANgOQgQgbgLgpIgNAZIgdgeQAVghANgpQANgqAFgyIAaAEQANACgBAOIgFAcIBZAAIAAApIgVAAIAAARQAABEgaA2IgIANQAXAZAlAZIgWAoQgUgPgPgOQgQgOgMgOQgOAPgQAOQgSAOgUAOIgTgZIgLAUQgYgRgYgNQglAXgxAOgAp9BLIAjAMQARgOAMgSIgxAAgAncgyQAKA0ARAiQASgmAAg7IAAgRIgkAAgAAKCMQAQgcAMgcQAMgeAHgfIAnAPQgHAfgNAhQgMAggRAfgAHmCfIgHgoIAYACQAMAAADgCQADgDAAgFIAAgfIhtAAIAAgcIgSAIIgRgfQAcgLAWgMIgSgSIAOgLQAIgFAHAGIANAPIAMgJIgVgVIAOgLQAHgGAIAGIANANQAKgLAHgLIgsAAQgMALgOALIgfAVIgTggQAbgPAUgRIgoAAIAAhCICBAAIgJgUIAggFQAIgBAFADQAFADAEAJIACALICAAAIAABCIgQAAIAAANQgLAbgbAeQANAIARAIQARAJAVAIIgSAiIgUgIIAAAdIhnAAIAAAvQAAAZgTAHQgKAEgPAAQgPAAgUgEgAGpAvIDqAAQgcgPgbgZIgBAAIAAATIh3AAIAAgQQgaAUghARgAJOgEQgOgQgMgSQgLgTgKgWIAAAOQgHAQgKAPQgKAQgNAOIBXAAIAAAAgAJkgiIAUgXIglAAQAHANAKAKgAGuhQQAOgOALgPIAXAGQAKACgFALIAAABIA4AAIgDgHIAZgHQAKgEAEALIADAGIBJAAIAAgUIjdAAgAD0CfIgJgrIAiAEQAMAAAEgCQAIgEABgJIAAjWIiOAAIAAEPIgrAAIAAk2IDkAAIAAERQAAAOgFAIQgGAIgLAEQgLAEgTAAQgRAAgYgEgAGCB8QAXgIATgKQATgKARgNIASAOQAIAIgHAIQgQAOgTAMQgUANgXAJgAJ0CFQgVgNgVgJIARgVQAHgIAKAFQARAHATAKQATAKAUAOIgbAhQgUgPgUgNgAlHCeIgIgsIAWACQAJAAADgDQADgDAAgFIAAg/IgiALIgIgsIAqgKIAAhAIgjAAIAAgnIAjAAIAAg7IAsAAIAAA7IAaAAIAAAnIgaAAIAAAyIAbgKIAAAnIgbAMIAABhQgBAYgQAIQgKAFgSAAQgMAAgQgCgAuvCPIAAgoIg7AfIgPguQAIgGAEgFQAEgGAAgEIAAheIgsAAIAAgqIBXAAIAAB/IAogUIAAAyIgXAOIBKAAIAAkFIAvAAIAABZIBPAAIAAApIhPAAIAACDIBYAAIAAApgACuBhIAAh3IBiAAIAAB3gADRA8IAcAAIAAguIgcAAgAAKgpIARgVQAEgGAFAAQAFgCAGAEQAcARAYAVIgaAiQghgcgegTgACogsIAAglIBsAAIAAAlgAAUiBIARgUQAEgGAEgBQAFgBAGADQAkAZAQAQIgaAhQghgdgdgUgAwIiGIARgVQAHgLAMAGQAoAaARAPIgZAkQgYgWgsgdgAsfkUQgbgKgUgOQgMgJgMgKQgLgLgKgNQgUAdglAVQglAVg2ALIgUgnQBZgRAjgqIh0AAIAAgnIAoAAIAAhWIBjAAIAAgeIAdAAQAHAAAEADQADAEAAAIIAAAPIBlAAIAABWIAqAAIAAAnIh8AAQAOAOAQALQARALAYAIQAYAIAgAHIgRAoQghgGgagKgAtnmOIA8AAIAAgvIg6AAgAvJmOIA2AAQACgMABgMIAAgXIg5AAgAjykLIgJgwQAsAFAHgDQAGgEAAgHIAAisIAvAAIAAC7QAAAagSALQgJAFgTACIgKAAQgRAAgWgCgAhTl5QgUgdgWgaIAZgQQAKgIAKANQArAvAfA4IgoAZQgRgggUgegAlUlZQAYgXATgaQAUgaAPgfIAYALQAOAGgGAPQgaA0gwA0gAA7m1QgMgEgKgKQgIgIgFgMQgFgMAAgPQAAgPAFgMQAFgNAIgJQAKgIAMgFQAMgFAPAAQAOAAAMAFQANAFAJAIQAJAJAFANQAFAMAAAPQAAAPgFAMQgFAMgJAIQgJAKgNAEQgMAEgOAAQgPAAgMgEgABBokQgKAFgGAHQgHAGgEAKQgEAKAAAMQAAALAEAJQADAKAIAHQAHAHAJAEQAJAEAMAAQAWAAAPgPQAHgHADgKQAEgJAAgLQAAgMgEgKQgDgKgHgGQgHgHgJgFQgKgDgLAAQgMAAgJADgAlPnXQAwgzAZhKIAfAIQAGABABAEQACAFgDAIIgEALIDKAAIAAAlIgYBFIgsgKIAVg2IitAAQgKAVgNATQgOATgQARgABmnUIgPgUIgEgEIgFgBIgCAAIAAAZIgRAAIAAhBIAeAAQAMAAAHAFQAHAFAAAJQAAAIgFAEQgEAFgHABIAUAcgABMn3IAHAAQAOAAAAgKQAAgGgEgCQgEgBgHgBIgGAAgAtQn2IAAgcIhUAAIAAAcIgtAAIAAgcIhGAAIAAgnIBGAAIAAgYIAtAAIAAAYIBUAAIAAgYIAtAAIAAAYIBKAAIAAAnIhKAAIAAAcg");
	this.shape.setTransform(108.9,62.9);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(2.9,3.2,212.1,119.4);


// stage content:
(lib._336x280_h5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});



this.frame_stop = function(){
		stopAnimation();
	}
	// logo
	this.instance = new lib.logo_1("synched",0);
	this.instance.setTransform(243.5,46.5,1,1,0,0,0,24.5,24.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).to({alpha:1},15,cjs.Ease.get(1)).wait(65).to({startPosition:0},0).to({y:-42.5},10,cjs.Ease.get(-1)).to({_off:true},1).wait(119).to({_off:false,y:46.5,alpha:0},0).to({alpha:1},15,cjs.Ease.get(1)).wait(75).to({startPosition:0},0).wait(1));

	// copy3
	this.instance_1 = new lib.copy3("synched",0);
	this.instance_1.setTransform(128.9,124,1,1,0,0,0,110.9,56);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(214).to({_off:false},0).to({alpha:1},15,cjs.Ease.get(1)).wait(80).to({startPosition:0},0).wait(1));

	// cta
	this.instance_2 = new lib.cta();
	this.instance_2.setTransform(189.8,239.9,1,1,0,0,0,42.8,9.9);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(224).to({_off:false},0).to({x:224.8,alpha:1},10,cjs.Ease.get(1)).to({x:219.8},5).wait(1).call(this.frame_stop).wait(71));

	// copy2
	this.instance_3 = new lib.copy2("synched",0);
	this.instance_3.setTransform(146.8,326.7,1,1,0,0,0,98.8,46.7);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(99).to({_off:false},0).to({y:61.7},15,cjs.Ease.get(0.98)).to({y:68.7},10).wait(75).to({startPosition:0},0).to({y:-70.4},10,cjs.Ease.get(-1)).wait(101));

	// img
	this.instance_4 = new lib._img_1();
	this.instance_4.setTransform(152.5,454.6,1,1,0,0,0,104.5,57.5);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(104).to({_off:false},0).to({x:154.5,y:207.5},15,cjs.Ease.get(0.98)).to({y:214.5},10).wait(75).to({y:-74.5},10,cjs.Ease.get(-1)).wait(96));

	// copy1
	this.instance_5 = new lib.copy1("synched",0);
	this.instance_5.setTransform(157.1,330,1,1,0,0,0,98.1,50);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(9).to({_off:false},0).to({y:130},15,cjs.Ease.get(1)).to({y:140},5).wait(65).to({startPosition:0},0).to({y:-75.4},10,cjs.Ease.get(-1)).wait(206));

	// bg
	this.instance_6 = new lib.bg_1("synched",0);
	this.instance_6.setTransform(180,150,1.1,1.1,0,0,0,180,150);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({scaleX:1,scaleY:1,alpha:1},9,cjs.Ease.get(1)).wait(300).to({startPosition:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,125,369.6,308);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;